version: '3.6'

services:
    go:
        container_name: go-shopping-cart
        image: appto-go
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            - '5000'
        ports:
            - '8050:5000'
        restart: unless-stopped
        networks:
            - appto
        env_file:
            -   .env
        volumes:
            - .:/go/src/${APP_NAME}:delegated
        depends_on:
            - pgsql

    pgsql:
        container_name: appto-pgsql
        image: postgres
        restart: unless-stopped
        ports:
            - 5432:5432
        networks:
            - appto
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./var:/var/lib/postgresql/data
            - ./local/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
    appto:
        name: appto_go
